from front_functions import GetApiCalls, PutApiCalls

get_api = GetApiCalls()
put_api = PutApiCalls()

print("basic connection check.")
print(get_api.get_hello_world())
print()
print("Creating user Charlie.")
print(put_api.put_create_user("Charlie"))
print("Creating user Renee.")
print(put_api.put_create_user("Renee"))
print()
print("Adding a note from Charlie")
print(put_api.put_add_todo("Charlie", "adding a note via frontend."))
print("adding a note from Renee.")
print(put_api.put_add_todo("Renee", "Continue being awsome and cute and great."))
print()
print("Checking if users exist.")
print(get_api.get_user("Charlie"))
print(get_api.get_user("Renee"))
print()
print("Getting notes from users.")
print(get_api.get_notes("Renee"))
print(get_api.get_notes("charlie"))
print()
print("In Progress notes from Charlie.")
print(get_api.get_notes_by_status("Charlie", "In Progress"))
print("New Notes from Charlie")
print(get_api.get_notes_by_status("Charlie", "New"))
print("getting complete notes from Renee.")
print(get_api.get_notes_by_status("Renee", "Complete"))
print()
